### ISSUE TITLE
Lienzo Panel not getting rebuilt from Json Object

### ISSUE THREAD

**Issue by aino-mahesh** [ahome-it/lienzo-core#76] opened 2015-06-12 07:15 UTC
Hello,
I am using lienzo for my diagram creation project. So I want to save my diagram which is created so I used Lienzo panel's toJsonString method which provided me with a Json String. Now I am using same json to recreate the lienzo panel from that same json String but it is not getting created.
I debugged the code and seems like the transformable property  in the internal  grid json object is causing problem along with the strokeWidth property used but if I remove them the structure is not getting created.

Please can someone help me.

**Comment by SprocketNYC** [comment] 2015-06-14 14:19
I'll check into it

**Comment by SprocketNYC** [comment] 2015-06-14 22:32
I've tried whole LienzoPanels with Grid's, CAN'T REPRODUCE. Are you trying to deserialize JSON from an OLD view?

Any more information, the stack or errors from the Parser Context would be helpful.

**Comment by aino-mahesh** [comment] 2015-06-15 05:12
Hi,
Yes, I was trying the same. I created my diagram on Grid Layer and then placed this layer on Linezo Panel, later took its json string and tried to reproduce the entire lienzo panel from JSONDeserializer.getInstance().fromString(jsonString) but then it was throwing exception:

java.lang.NullPointerException
	at com.emitrom.lienzo.client.core.shape.json.AbstractFactory.getAttributeType(AbstractFactory.java:102)
	at com.emitrom.lienzo.client.core.shape.json.JSONDeserializer.validateAttributes(JSONDeserializer.java:275)
	at com.emitrom.lienzo.client.core.shape.json.JSONDeserializer.fromJSON(JSONDeserializer.java:217)
	at com.emitrom.lienzo.client.core.shape.json.JSONDeserializer.fromString(JSONDeserializer.java:103)
	at com.emitrom.lienzo.client.core.shape.json.JSONDeserializer.fromString(JSONDeserializer.java:64)
	at com.ainosoft.client.labeldesigner.LabelDesignerPresenterTest.testJson(LabelDesignerPresenterTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.google.gwt.junit.client.impl.GWTTestAccessor.invoke(GWTTestAccessor.java:39)
	at com.google.gwt.junit.client.impl.GWTRunner.executeTestMethod(GWTRunner.java:226)
	at com.google.gwt.junit.client.GWTTestCase.doRunTest(GWTTestCase.java:157)
	at junit.framework.TestCase.runTest(TestCase.java:59)
	at com.google.gwt.junit.client.GWTTestCase.runBare(GWTTestCase.java:151)
	at com.google.gwt.junit.client.GWTTestCase.__doRunTest(GWTTestCase.java:115)
	at com.google.gwt.junit.client.impl.GWTRunner.runTest(GWTRunner.java:302)
	at com.google.gwt.junit.client.impl.GWTRunner.doRunTest(GWTRunner.java:235)
	at com.google.gwt.junit.client.impl.GWTRunner.access$9(GWTRunner.java:229)
	at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:106)
	at com.google.gwt.junit.client.impl.GWTRunner$InitialResponseListener.onSuccess(GWTRunner.java:61)
	at com.google.gwt.junit.client.impl.GWTRunner$InitialResponseListener.onSuccess(GWTRunner.java:1)
	at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.onResponseReceived(RequestCallbackAdapter.java:232)
	at com.google.gwt.http.client.Request.fireOnResponseReceived(Request.java:250)
	at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:341)
	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:222)
	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296)
	at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551)
	at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
	at java.lang.Thread.run(Thread.java:722)

Later I tried out same by just picking up json for just the grid layer but the exception was he same. When I debugged the code I figured that the instance we get from the IFactory doesnt contain the property transformable and for strokeWidth.

Below is the json:

{"type":"GridLayer", "attributes":{"visible":true, "listening":true, "clearLayerBeforeDraw":true, "transformable":true}, "children":[{"type":"Rectangle", "attributes":{"visible":true, "listening":true, "x":198, "y":65, "alpha":1, "draggable":true, "width":500, "height":100, "dragConstraint":"none", "scale":{"x":1, "y":1}, "strokeWidth":3, "cornerRadius":0}},{"type":"Rectangle", "attributes":{"visible":true, "listening":true, "x":215, "y":79, "alpha":1, "draggable":true, "width":200, "height":70, "fill":"#ffa500", "dragConstraint":"none", "scale":{"x":1, "y":1}}},{"type":"Rectangle", "attributes":{"visible":true, "listening":true, "x":198, "y":167, "alpha":1, "draggable":true, "width":500, "height":150, "fill":"#c0c0c0", "dragConstraint":"none", "scale":{"x":1, "y":1}}},{"type":"Rectangle", "attributes":{"visible":true, "listening":true, "x":430, "y":80, "alpha":1, "draggable":true, "width":250, "height":70, "fill":"#ffa500", "dragConstraint":"none", "scale":{"x":1, "y":1}}},{"type":"Rectangle", "attributes":{"visible":true, "listening":true, "x":446, "y":168, "alpha":1, "draggable":true, "width":1, "height":147, "dragConstraint":"none", "scale":{"x":1, "y":1}, "strokeWidth":5}},{"type":"Rectangle", "attributes":{"visible":true, "listening":true, "x":220, "y":189, "alpha":1, "draggable":true, "width":200, "height":100, "fill":"lightblue", "dragConstraint":"none", "scale":{"x":1, "y":1}}},{"type":"Rectangle", "attributes":{"visible":true, "listening":true, "x":472, "y":189, "alpha":1, "draggable":true, "width":200, "height":100, "fill":"lightblue", "dragConstraint":"none", "scale":{"x":1, "y":1}}}], "lines":[{"type":"Line", "attributes":{"visible":true, "listening":true, "x":0, "y":0, "alpha":1, "draggable":false, "points":[{"x":0, "y":448},{"x":1000, "y":448}], "stroke":"#cccccc", "strokeWidth":0, "dashArray":[]}},{"type":"Line", "attributes":{"visible":true, "listening":true, "x":0, "y":0, "alpha":1, "draggable":false, "points":[{"x":0, "y":448},{"x":1000, "y":448}], "stroke":"#cccccc", "strokeWidth":0, "dashArray":[]}},{"type":"Line", "attributes":{"visible":true, "listening":true, "x":0, "y":0, "alpha":1, "draggable":false, "points":[{"x":0, "y":0},{"x":1000, "y":450}], "stroke":"#cccccc", "dashArray":[5,5], "strokeWidth":0}},{"type":"Line", "attributes":{"visible":true, "listening":true, "x":0, "y":0, "alpha":1, "draggable":false, "points":[{"x":0, "y":0},{"x":1000, "y":450}], "stroke":"#cccccc", "dashArray":[5,5], "strokeWidth":0}}], "sizes":[8,8,8,8]}

**Comment by SprocketNYC** [comment] 2015-06-15 11:09
OK, will look into it. Usually GridLayer's are not part of the Scene Graph, they are set as the Background Layer, and when serializing a LienzoPanel/Viewport, the toolkit does not serialize out the Background Layer, so I'm not totally surprised no one has hit this before, because it's generally not used this way. GridLayer is used more for decoration. Still it should deserialize, so I'll have to code up something to test this case.

**Comment by SprocketNYC** [comment] 2015-06-15 20:04
Seems to be fixed, will be in 118-SNAPSHOT

You really shouldn't be adding GridLayer's to the main scene graph, but I seem to have made it work anyway....

**Closed by SprocketNYC** 2015-06-15 20:04 UTC
Labels: bug

**Comment by SprocketNYC** [comment] 2015-06-15 20:07
118 is in sonatype snapshots
